### ISSUE TITLE
Transform data related to geolocalization

### ISSUE THREAD

**Issue by robperch** [Roberto919/intro_ds_lab1#17]
Follow the following instructions specified in the lab's instructions:
- [x] Agregar la variable `latitud` y `longitud` generadas a partir de la column `geo_point`.
- [x] Pasar la variable `latitud` y `longitud` a numérica -si no la tomó como numérica-.
- [x] Eliminar la columna `geo_point` -una vez que creaste la variable `latitud` y `longitud`.
- [x] Eliminar la columna `geo_shape`.

**Comment by Acturio** [comment]
Terminado
