### ISSUE TITLE
Generea el profiling de variables categóricas

### ISSUE THREAD

**Issue by robperch** [Roberto919/intro_ds_lab1#24]
- [x] Categories
    - [x] Número de categorías
    - [x] Valor de las categorías
    - [x] Moda
    - [x] Valores faltantes
    - [x] Número de observaciones con valores faltantes
    - [x] Proporción de observaciones por categoría
    - [x] Top 1, top 2, top 3 (moda 1, moda 2, moda 3)
    - [x] Faltas de ortografía ?

**Comment by codeMariana** [comment]
Se complementa con issue 43
