### ISSUE TITLE
Data profiling  Coordenadas geoespaciales

### ISSUE THREAD

**Issue by EddOselotl** [Roberto919/intro_ds_lab1#30]
Print information about the precision related with geospatial measures

**Comment by robperch** [comment]
Hey @EddOselotl, estaba revisando esta tarea pero creo que no hay nada que solucionar. Actualmente tenemos ya las columnas de `Latitud` y `Longitud` separadas y como valores numéricos. Creo que ya están en el formato correcto y realmente no hay nada que debamos hacerles. Según yo ya están limpias y listas (Anexo imagen).

![Screen Shot 2020-10-01 at 12 02 49](https://user-images.githubusercontent.com/48889991/94840431-08c9d480-03de-11eb-9081-d2814cfc82fb.png)

Si estás de acuerdo con esto, avísame para que cerremos este issue lo antes posible y me asigne alguno otro.
