### ISSUE TITLE
GEDA Variables Numéricas

### ISSUE THREAD

**Issue by codeMariana** [Roberto919/intro_ds_lab1#60]
- [x] Histograma: Simetría/Asimetría, huecos, multimodalidad, aproximación a una distribución empírica. Una variable (numérica o categórica). @codeMariana 
- [x] Diagrama de caja y brazos -boxplot-: outliers, amontonamientos. Cuartiles 25%, 50%, 75%. @codeMariana 
- [x] Scatterplot: Cada dato es un punto, permite identificar huecos. Dos variables numéricas. Identificar relación (co) entre variables por ejemplo explicativa y output. @EddOselotl 
- [x] Rugplot: Gráfica que agrega pequeñas líneas verticales (eje x) u horizontales (eje y), se ocupa como un extra a un scatterplot. @Roberto919 
- [x] Density estimate: Como un modelo de tus datos... solo ten cuidado con los límites de las variables. @Roberto919 
- [x] Distribution estimate: Permite comparar distribuciones como por ejemplo si una está adelante de otra. @EddOselotl *No se incorpora debido que es parecido al density estimase e histogramas.*
- [x] QQ-plot: Permite comparar dos distribuciones, la tuya vs una teórica (por default la normal). @Acturio 
- [x] Matriz de correlación: Permite identificar correlaciones entre variables. @Acturio

**Comment by robperch** [comment]
Creo que podríamos juntar el histograma y el rugplot en uno solo. Qué opinas @codeMariana?
Creo que podríamos usar esta librería -> https://plotly.com/python/distplot/

**Comment by robperch** [comment]
Me parece que el *Density plot* y el *Histograma* hacen realmente lo mismo. No estoy tan seguro que agregue valor tener los dos. Creo que es suficiente que hagamos la función para una de las dos.
