### ISSUE TITLE
Preguntas valiosas para análisis

### ISSUE THREAD

**Issue by robperch** [Roberto919/intro_ds_lab1#70]
**El objetivo del ejercicio es que cada quien haga exploraciones a través de las preguntas que planteó para intentar sacar insights relevantes para la construcción del modelo.**

## Preguntas e insights

@codeMariana 
- [x] ¿Cómo se distribuye el consumo (total, promedio) por categoría de `indice_des`?
- [x] ¿Cómo se distribuye el consumo (total, promedio) por categoría de `indice_des` por `alcaldía`?
- [x] ¿Cómo se distribuye el consumo (total, promedio) por categoría de `indice_des` por `bimestre`? 
- [x] ¿Cómo se distribuye el consumo (total, promedio) por categoría de `indice_des` por `colonia` (top 15 con más observaciones)?

@Acturio 
- [x] ¿En cuántas manzanas y colonias el consumo total es cero? Y, agrupando por alcaldías, ¿en cuántas el consumo total es cero?
- [x] ¿Cuántas observaciones nulas o ceros del consumo (total,promedio) hay por `alcaldía`?

@Roberto919 
- [x] ¿Cómo se distribuye geoespacialmente la variable respuesta `indice_des`? 
    - Rob: Después de investigar acerca de como podríamos visualizar los datos para responder esta pregunta, llegué a la conclusión de que está muy complicado para mí y no se obtendría algo tan valioso. Creo que no vale la pena indagar más en esta pregunta.
- [x] ¿Cómo se comporta la clasificación del `indice_des` por las colonias a lo largo de los `bimestres`? *No se consideró visualmente relevante*
- [x] ¿Qué porcentaje del consumo es para doméstico, no doméstico y mixto?
- [x] ¿Cómo ha cambiado la distribución de la variable `indice_des` a lo largo de los distintos bimestres? *No se consideró visualmente relevante*
- [x] ¿Qué tan consistente se clasifica la variable `colonia` con el `indice_des`?
    - No hay mucha consistencia en la clasificación. Solo el 21% de las las colonias fueron consistentemente clasificadas con una sola etiqueta de la variable `indice_des`.
<img width="600" alt="Screen Shot 2020-10-14 at 17 14 26" src="https://user-images.githubusercontent.com/48889991/96051249-b7d7c880-0e40-11eb-80a6-eea30004a2db.png">

@EddOselotl 
- [x] Predecir índice de consumo `indice_des` con variables numéricas de totales. *No es parte del GEDA*
- [x] ¿Cuál es la alcaldía y colonia que consume más agua (consumo_total) y cuál es la que menos consume?
- [x] Cual es el índice de consumo `indice_des` por `alcaldía`(correlación entre variables categóricas)
    - Rob: Con el mapa de calor por alcaldía podemos ver que sí hay ubicaciones específicas con una tendencia clara a ser clasificadas con un `indice_des` particular (e.g. si el registro es de Azcapotzalco, tenderá a ser clasificado como "bajo"). (el mapa de calor muestra la proporción de conteos de cada clasificación por alcaldía)
![Screen Shot 2020-10-14 at 14 31 58](https://user-images.githubusercontent.com/48889991/96036402-062d9d00-0e2a-11eb-9241-58a8c36bbd8f.png)

**Comment by codeMariana** [comment]
Mis preguntas son las primeras 6. @EddOselotl creo que va a revisar la distribución espacial.

**Comment by codeMariana** [comment]
Agregué una séptima pregunta, ya que revisando el EDA, me di cuenta que para todos los consumos, el valor top 1 es cero. Como el nivel de granularidad de los datos es colonia, ¿hay muchas colonias con sin consumo de agua? ¿Es correcto eso? Por eso agregué la parte de agrupar por alcaldía.

**Comment by EddOselotl** [comment]
para esa ultima pregunta creo que no es viable  mostrar por colonia dado que son bastantes y algunas solo aparecen una vez.

**Comment by codeMariana** [comment]
Entendido. Tus últimas 3 preguntas @EddOselotl  creo que son las mismas que yo puse arriba, ¿no? ¿O te refieres a sacar la correlación entre índice_des con el consumo, más que la distribución, o la interacción entre categóricas únicamente? El índice_des no es de consumo, es de desarrollo. 

Apenas ayer me di cuenta que solo es un año. Voy a quitar ese bullet de la distribución por año.

**Comment by Acturio** [comment]
Ya están contestadas en la pres mis preguntas. Dejaré el espacio para la respuesta de las suyas
